--- # roles/airflow/tasks/main.yml

- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: Centos.yml
  when: ansible_os_family in ("Centos", "RedHat")


- include: Windows.yml
  when: ansible_os_family == "Windows"

- include: common.yml
  when: ansible_os_family in ("Centos", "Debian", "Darwin")
